title: "First Baptist Church Muncie"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fbcmuncie.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter: fbcmuncie
facebook: firstbaptistmuncie
flickr: fbcmuncie
youtube: fbcmunciesermons
phone: 765-284-7749
address: 309 E. Adams Street</br> Muncie, Indiana 47305
mission: A Spirit-led people gathered to discover and join God's presence in our community
# Capital Campaign Numbers
pledged: $305,405
collected: $133,695
# worship: "9:15 AM (Traditional), 10:45 AM (Contemporary)"
worship: "We will gather in a combined worship gathering this week at 10:45 AM"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - 
    scope:
     path: ""
     type: "people"
    values:
     layout: "people"

collections:
  questions:
  people:
      output: true
      permalink: /:title
  worship:
  visitors:
  news:
  quotes:

permalink: /:categories/:year/:month/:day/:title
